import Link from "next/link";
import { ArrowRight, BarChart3, Bot, Check, Globe2, Search, Workflow } from "lucide-react";
import { CTA } from "@/components/cta";

const intelligencePillars = [{ icon: Search, title: "See the signal", text: "Bring leads, pipeline movement, follow-up, and operating evidence into one working view." }, { icon: Workflow, title: "Take the next step", text: "Turn important signals into assigned work and controlled playbooks instead of another forgotten dashboard." }, { icon: BarChart3, title: "Keep the proof", text: "Trace activity, sender identity, and outcomes through an audit trail built for accountable growth." }];
const services = [{ n: "01", title: "Revenue Rescue Website", text: "A conversion system built to turn hard-earned attention into qualified opportunities." }, { n: "02", title: "Lead Recovery Automation", text: "Instant response, missed-call text back, nurture, and pipeline follow-through." }, { n: "03", title: "AI Search Visibility", text: "Technical, local, and answer-engine visibility designed for how buyers search now." }, { n: "04", title: "Custom Growth Systems", text: "Focused tools, dashboards, and automations built around your real bottleneck." }];

export default function Home() { return <>
  <section id="growthos" className="noise grid-lines overflow-hidden border-b border-white/10"><div className="shell relative grid min-h-[calc(100vh-76px)] gap-12 py-16 lg:grid-cols-[1.15fr_.85fr] lg:items-center lg:py-24">
    <div className="relative z-10"><p className="eyebrow">Introducing GrowthOS™ · Business Intelligence Ecosystem</p><h1 className="mt-7 max-w-5xl font-display text-[clamp(4.2rem,9vw,9rem)] font-semibold leading-[.75] tracking-[-.055em]">Turn business <em className="font-normal text-forge-lime">signals</em> into your next best move.</h1><p className="mt-8 max-w-2xl text-base leading-7 text-white/65 sm:text-lg">GrowthOS brings your leads, pipeline, follow-up, and operating evidence into one command center—helping your team spot missed opportunities, act through safe automations, and see what actually moves revenue.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link className="btn-primary" href="#growthos-details">Explore GrowthOS <ArrowRight size={17} /></Link><Link className="btn-secondary" href="/revenue-rescue">Run the Revenue Rescue Scan</Link></div></div>
    <div className="relative z-10 lg:pl-8"><div className="mx-auto max-w-md rotate-2 rounded-[2rem] border border-white/15 bg-[#111815] p-4 shadow-2xl shadow-black/40"><div className="rounded-[1.5rem] border border-white/10 bg-forge-ink p-7"><div className="flex items-start justify-between gap-4"><div><p className="eyebrow">GrowthOS intelligence</p><p className="mt-2 text-sm text-white/45">Today&apos;s opportunity snapshot</p></div><span className="shrink-0 rounded-full bg-forge-lime/10 px-3 py-1 text-xs font-bold text-forge-lime">Signals active</span></div><div className="mt-10 flex items-end gap-4"><span className="font-display text-8xl font-semibold leading-none">03</span><span className="max-w-24 pb-3 text-sm leading-5 text-white/35">priority signals</span></div><div className="mt-8 space-y-4">{[["Stale high-intent leads", "Review"], ["Follow-up due today", "Ready"], ["Pipeline activity", "Tracked"]].map(([item, status], i) => <div key={item} className="flex items-center justify-between gap-4 border-t border-white/10 pt-4 text-sm"><span className="text-white/65">0{i + 1} &nbsp; {item}</span><span className="text-forge-lime">{status}</span></div>)}</div></div></div></div>
  </div></section>
  <section className="bg-forge-cream py-6 text-forge-ink"><div className="shell flex flex-wrap items-center justify-between gap-4 text-xs font-extrabold uppercase tracking-[.16em]"><span>See the signal</span><span className="text-black/20">✦</span><span>Prioritize the next move</span><span className="text-black/20">✦</span><span>Execute safely</span><span className="text-black/20">✦</span><span>Keep the evidence</span></div></section>
  <section id="growthos-details" className="shell py-24 sm:py-32"><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow">The GrowthOS advantage</p><h2 className="mt-5 font-display text-5xl font-semibold leading-[.92] sm:text-7xl">Your business already generates the clues.</h2></div><div><p className="max-w-3xl text-2xl leading-snug text-white/70 sm:text-3xl">GrowthOS turns scattered business activity into a clear view of what needs attention, what your team should do next, and what happened after they acted.</p><div className="mt-14 grid gap-5 md:grid-cols-3">{intelligencePillars.map(({ icon: Icon, title, text }) => <article key={title} className="rounded-3xl border border-white/10 bg-white/[.03] p-6"><Icon className="text-forge-lime" /><h3 className="mt-8 text-lg font-extrabold">{title}</h3><p className="mt-3 text-sm leading-6 text-white/50">{text}</p></article>)}</div></div></div></section>
  <section className="bg-forge-moss py-24 sm:py-32"><div className="shell"><div className="max-w-3xl"><p className="eyebrow">The MogulForge product suite</p><h2 className="mt-5 font-display text-5xl font-semibold leading-[.92] sm:text-7xl">Two products. One shared purpose.</h2><p className="mt-7 max-w-2xl text-lg leading-7 text-white/60">Revenue Rescue finds and prioritizes the leaks. GrowthOS gives the business an operating system for acting on signals, managing follow-up, and keeping the evidence.</p></div><div className="mt-14 grid border-y border-white/15 lg:grid-cols-2"><article className="border-b border-white/15 py-10 lg:border-b-0 lg:border-r lg:pr-12"><span className="text-xs font-bold uppercase tracking-[.18em] text-forge-lime">01 · Intelligence ecosystem</span><h3 className="mt-10 font-display text-5xl font-semibold">GrowthOS BIE</h3><p className="mt-5 max-w-xl leading-7 text-white/55">A continuous command center for leads, pipeline movement, follow-up, controlled playbooks, operating evidence, and auditability.</p><Link href="#growthos-details" className="mt-8 inline-flex items-center gap-2 border-b border-forge-lime pb-1 text-sm font-extrabold text-forge-lime">Explore GrowthOS <ArrowRight size={16}/></Link></article><article className="py-10 lg:pl-12"><span className="text-xs font-bold uppercase tracking-[.18em] text-forge-lime">02 · Diagnostic and recovery</span><h3 className="mt-10 font-display text-5xl font-semibold">Revenue Rescue</h3><p className="mt-5 max-w-xl leading-7 text-white/55">A focused scan and recovery path that exposes conversion, visibility, and follow-up leaks, then ranks the next moves by opportunity.</p><Link href="/revenue-rescue" className="mt-8 inline-flex items-center gap-2 border-b border-forge-lime pb-1 text-sm font-extrabold text-forge-lime">Run the Revenue Rescue Scan <ArrowRight size={16}/></Link></article></div></div></section>
  <section id="score" className="bg-forge-cream py-24 text-forge-ink sm:py-32"><div className="shell grid gap-14 lg:grid-cols-2 lg:items-center"><div className="rounded-[2rem] bg-forge-ink p-8 text-white sm:p-12"><div className="flex items-center gap-2 text-forge-lime"><BarChart3 size={18}/><span className="text-xs font-extrabold uppercase tracking-[.18em]">MogulScore™</span></div><div className="mt-12 grid grid-cols-[auto_1fr] items-end gap-8"><span className="font-display text-8xl font-semibold sm:text-9xl">78</span><div className="pb-4"><p className="text-sm text-white/45">Market readiness</p><div className="mt-3 h-2 rounded-full bg-white/10"><div className="h-2 w-[78%] rounded-full bg-forge-lime" /></div></div></div><div className="mt-10 grid gap-3 sm:grid-cols-2">{["Conversion clarity", "Local visibility", "AI discoverability", "Follow-up speed"].map(x => <div key={x} className="flex items-center gap-2 rounded-xl bg-white/5 p-3 text-xs text-white/65"><Check size={14} className="text-forge-lime" />{x}</div>)}</div></div><div><p className="eyebrow !text-forge-rust">The intelligence layer</p><h2 className="mt-5 font-display text-5xl font-semibold leading-[.92] sm:text-7xl">Know exactly where you’re leaving money behind.</h2><p className="mt-7 max-w-xl leading-7 text-black/60">MogulScore™ measures the signals that shape whether a buyer finds you, trusts you, contacts you, and gets converted. It turns a vague growth problem into a ranked recovery plan.</p><Link href="/revenue-rescue" className="mt-8 inline-flex items-center gap-2 border-b-2 border-black pb-1 text-sm font-extrabold">Get your score <ArrowRight size={16}/></Link></div></div></section>
  <section id="services" className="shell py-24 sm:py-32"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="eyebrow">What we forge</p><h2 className="mt-5 font-display text-5xl font-semibold sm:text-7xl">Systems that pay rent.</h2></div><p className="max-w-md text-sm leading-6 text-white/50">No disconnected deliverables. Every build is tied to a measurable leak in the customer journey.</p></div><div className="mt-14 border-t border-white/15">{services.map(s => <Link href={`/services#${s.n}`} key={s.n} className="group grid gap-5 border-b border-white/15 py-8 transition hover:bg-white/[.025] md:grid-cols-[80px_1fr_1fr_auto] md:items-center"><span className="text-xs font-bold text-forge-lime">{s.n}</span><h3 className="text-xl font-extrabold sm:text-2xl">{s.title}</h3><p className="max-w-lg text-sm leading-6 text-white/45">{s.text}</p><ArrowRight className="transition group-hover:translate-x-1 group-hover:text-forge-lime" /></Link>)}</div></section>
  <section className="border-t border-white/10"><div className="shell grid gap-10 py-24 lg:grid-cols-2 lg:items-center"><div><p className="eyebrow">Built for practical growth</p><h2 className="mt-5 font-display text-5xl font-semibold leading-[.92] sm:text-7xl">AI where it matters. Humans where it counts.</h2></div><div className="grid grid-cols-2 gap-4">{[[Globe2,"Findable"],[Bot,"Responsive"],[Workflow,"Connected"],[BarChart3,"Measurable"]].map(([Icon,label]) => { const I = Icon as typeof Globe2; return <div key={label as string} className="rounded-2xl border border-white/10 p-5"><I className="text-forge-lime"/><p className="mt-8 font-bold">{label as string}</p></div>})}</div></div></section>
  <CTA />
</>; }

