"use client";
import { useState } from "react";
import { useForm } from "react-hook-form";
import type { RescueInput } from "@/lib/rescue-schema";

type RescueResult = { score:number; estimatedMonthlyLeakage:string; topLeaks:{title:string;impact:string;fix:string}[]; quickWins:string[]; summary:string };
const fields = [{name:"businessName",label:"Business name",type:"text"},{name:"website",label:"Website",type:"url"},{name:"industry",label:"Industry",type:"text"},{name:"serviceArea",label:"Service area",type:"text"},{name:"averageJobValue",label:"Average job value ($)",type:"number"},{name:"monthlyLeadVolume",label:"Monthly lead volume",type:"number"}] as const;

export function RescueForm(){
  const { register, handleSubmit, formState:{errors,isSubmitting} } = useForm<RescueInput>();
  const [result,setResult]=useState<RescueResult|null>(null); const [error,setError]=useState("");
  const submit=async(data:RescueInput)=>{ setError(""); const res=await fetch("/api/revenue-rescue",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)}); const body=await res.json(); if(!res.ok){setError(body.error??"Unable to run the scan.");return;} setResult(body.result); };
  if(result) return <div className="rounded-[2rem] border border-forge-lime/30 bg-white/[.04] p-7 sm:p-10"><p className="eyebrow">Your first-pass Revenue Rescue Score</p><div className="mt-6 font-display text-8xl font-semibold text-forge-lime">{result.score}<span className="text-2xl text-white/30">/100</span></div><p className="mt-5 max-w-2xl text-white/65">{result.summary}</p><p className="mt-5 text-lg font-extrabold">Estimated monthly leakage: <span className="text-forge-lime">{result.estimatedMonthlyLeakage}</span></p><div className="mt-9 space-y-4">{result.topLeaks.map(leak=><div key={leak.title} className="rounded-xl border border-white/10 p-5"><h3 className="font-extrabold">{leak.title}</h3><p className="mt-2 text-sm text-white/50">{leak.impact}</p><p className="mt-3 text-sm text-forge-lime">Next move: {leak.fix}</p></div>)}</div><button onClick={()=>setResult(null)} className="btn-secondary mt-7">Run another scan</button></div>;
  return <form onSubmit={handleSubmit(submit)} className="grid gap-5 rounded-[2rem] border border-white/10 bg-white/[.03] p-6 sm:grid-cols-2 sm:p-10">{fields.map(f=><label key={f.name} className="grid gap-2 text-sm font-bold">{f.label}<input {...register(f.name,{required:true})} type={f.type} className="rounded-xl border border-white/15 bg-transparent px-4 py-3 outline-none focus:border-forge-lime"/>{errors[f.name]&&<span className="text-xs text-forge-rust">Required</span>}</label>)}<label className="grid gap-2 text-sm font-bold sm:col-span-2">Current follow-up process<textarea {...register("followUpProcess",{required:true})} rows={3} className="rounded-xl border border-white/15 bg-transparent px-4 py-3 outline-none focus:border-forge-lime"/></label><label className="grid gap-2 text-sm font-bold sm:col-span-2">Biggest sales challenge<textarea {...register("biggestChallenge",{required:true})} rows={3} className="rounded-xl border border-white/15 bg-transparent px-4 py-3 outline-none focus:border-forge-lime"/></label>{error&&<p className="text-sm text-forge-rust sm:col-span-2">{error}</p>}<button disabled={isSubmitting} className="btn-primary sm:col-span-2" type="submit">{isSubmitting?"Analyzing your revenue path…":"Reveal my revenue leaks"}</button><p className="text-center text-xs text-white/35 sm:col-span-2">This is a directional assessment based on the information you provide—not a guarantee of revenue.</p></form>;
}

